// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Nubrio.Infrastructure.Persistence;

#nullable disable

namespace Nubrio.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NubrioDbContext))]
    [Migration("20251214085016_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nubrio.Domain.Models.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("TimeZoneIana")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("time_zone_iana");

                    b.HasKey("Id")
                        .HasName("pk_locations");

                    b.ToTable("locations", (string)null);
                });

            modelBuilder.Entity("Nubrio.Domain.Models.Location", b =>
                {
                    b.OwnsOne("Nubrio.Domain.Models.Coordinates", "Coordinates", b1 =>
                        {
                            b1.Property<Guid>("LocationId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("longitude");

                            b1.HasKey("LocationId");

                            b1.ToTable("locations");

                            b1.WithOwner()
                                .HasForeignKey("LocationId")
                                .HasConstraintName("fk_locations_locations_id");
                        });

                    b.OwnsOne("Nubrio.Domain.Models.ExternalLocationId", "ExternalLocationId", b1 =>
                        {
                            b1.Property<Guid>("LocationId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("ProviderName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("external_provider");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("external_id");

                            b1.HasKey("LocationId");

                            b1.HasIndex("ProviderName", "Value")
                                .IsUnique()
                                .HasDatabaseName("ix_locations_external_provider_external_id");

                            b1.ToTable("locations");

                            b1.WithOwner()
                                .HasForeignKey("LocationId")
                                .HasConstraintName("fk_locations_locations_id");
                        });

                    b.Navigation("Coordinates")
                        .IsRequired();

                    b.Navigation("ExternalLocationId")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
