// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Nubrio.Infrastructure.Persistence;

#nullable disable

namespace Nubrio.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NubrioDbContext))]
    partial class NubrioDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nubrio.Domain.Models.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("TimeZoneIana")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("time_zone_iana");

                    b.HasKey("Id")
                        .HasName("pk_locations");

                    b.ToTable("locations", (string)null);
                });

            modelBuilder.Entity("Nubrio.Infrastructure.Persistence.Entities.Request", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool?>("CacheHit")
                        .HasColumnType("boolean")
                        .HasColumnName("cache_hit");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("endpoint");

                    b.Property<int>("LatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("latency_ms");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp_utc");

                    b.HasKey("Id")
                        .HasName("pk_requests");

                    b.HasIndex("TimestampUtc", "City")
                        .HasDatabaseName("ix_requests_timestamp_utc_city");

                    b.HasIndex("TimestampUtc", "Id")
                        .HasDatabaseName("ix_requests_timestamp_utc_id");

                    b.ToTable("requests", (string)null);
                });

            modelBuilder.Entity("Nubrio.Domain.Models.Location", b =>
                {
                    b.OwnsOne("Nubrio.Domain.Models.Coordinates", "Coordinates", b1 =>
                        {
                            b1.Property<Guid>("LocationId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("longitude");

                            b1.HasKey("LocationId");

                            b1.ToTable("locations");

                            b1.WithOwner()
                                .HasForeignKey("LocationId")
                                .HasConstraintName("fk_locations_locations_id");
                        });

                    b.OwnsOne("Nubrio.Domain.Models.ExternalLocationId", "ExternalLocationId", b1 =>
                        {
                            b1.Property<Guid>("LocationId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("ProviderName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("external_provider");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("external_id");

                            b1.HasKey("LocationId");

                            b1.HasIndex("ProviderName", "Value")
                                .IsUnique()
                                .HasDatabaseName("ix_locations_external_provider_external_id");

                            b1.ToTable("locations");

                            b1.WithOwner()
                                .HasForeignKey("LocationId")
                                .HasConstraintName("fk_locations_locations_id");
                        });

                    b.Navigation("Coordinates")
                        .IsRequired();

                    b.Navigation("ExternalLocationId")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
